name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to App Engine
      uses: GoogleCloudPlatform/github-actions/app-engine-deploy@master
      with:
        project_id: houndly-chatbot
        version: ${{ github.sha }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}